// API Key for OpenWeatherMap
export const API_KEY = "12f662f1634345bffc0633f5f77da1db"

// Recife coordinates
export const RECIFE_LAT = -8.0476
export const RECIFE_LON = -34.877

// Lista de bairros de Recife
export const bairrosRecife = [
  "Aflitos",
  "Afogados",
  "Água Fria",
  "Alto José Bonifácio",
  "Alto José do Pinho",
  "Alto do Mandu",
  "Alto do Pascoal",
  "Alto Santa Teresinha",
  "Apipucos",
  "Areias",
  "Arruda",
  "Barro",
  "Beberibe",
  "Benfica",
  "Boa Viagem",
  "Boa Vista",
  "Bomba do Hemetério",
  "Bongi",
  "Brasília Teimosa",
  "Brejo do Beberibe",
  "Brejo da Guabiraba",
  "Cabanga",
  "Caçote",
  "Cajueiro",
  "Campina do Barreto",
  "Campo Grande",
  "Casa Amarela",
  "Casa Forte",
  "Caxangá",
  "Cidade Universitária",
  "Coelhos",
  "Cohab",
  "Comunidade do Pilar",
  "Coque",
  "Coqueiral",
  "Cordeiro",
  "Córrego do Jenipapo",
  "Curado",
  "Derby",
  "Dois Irmãos",
  "Dois Unidos",
  "Encruzilhada",
  "Engenho do Meio",
  "Entra Apulso",
  "Espinheiro",
  "Estância",
  "Fundão",
  "Graças",
  "Guabiraba",
  "Hipódromo",
  "Ibura",
  "Ilha Joana Bezerra",
  "Ilha do Leite",
  "Ilha do Retiro",
  "Imbiribeira",
  "Ipsep",
  "Iputinga",
  "Jaqueira",
  "Jardim São Paulo",
  "Jiquiá",
  "Jordão",
  "Linha do Tiro",
  "Macaxeira",
  "Madalena",
  "Mangabeira",
  "Mangueira",
  "Monteiro",
  "Morro da Conceição",
  "Mustardinha",
  "Nova Descoberta",
  "Paissandu",
  "Parnamirim",
  "Passarinho",
  "Pau Ferro",
  "Peixinhos",
  "Pina",
  "Poço da Panela",
  "Ponte d'Uchoa",
  "Ponto de Parada",
  "Porto da Madeira",
  "Prado",
  "Recife",
  "Rosarinho",
  "San Martin",
  "Sancho",
  "Santana",
  "Santo Amaro",
  "Santo Antônio",
  "São José",
  "Setúbal",
  "Sítio dos Pintos",
  "Soledade",
  "Tamarineira",
  "Tejipió",
  "Torre",
  "Torreão",
  "Torrões",
  "Totó",
  "Várzea",
  "Vasco da Gama",
  "Vila Tamandaré",
  "Zumbi",
]

// Categorias de alerta
export const categorias = [
  { id: "alagamento", nome: "Alagamento" },
  { id: "deslizamento", nome: "Deslizamento" },
  { id: "bueiro", nome: "Bueiro aberto" },
  { id: "enchente", nome: "Enchente" },
  { id: "queda_arvore", nome: "Queda de árvore" },
]

